### ISSUE TITLE
Cannot install release version

### ISSUE THREAD

**Issue by mdhsl** [opensensorhub/osh-android#10]
Since using the last version of the APP, after building using `./gradlew build`, I cannot install the release APK, the error message is "the app is corrupted".
The debug one worked anyway

Phone: S7
Android version: Nougat 7.0

**Comment by alexrobin** [comment]
I cannot reproduce this exact issue. However the release build cannot be installed as-is as you'll get a different error message that says the app needs to be signed before it can be installed. This is intended  behavior and signing can be done from IntelliJ IDEA for instance, see https://developer.android.com/studio/publish/app-signing.html#sign-apk

**Comment by mdhsl** [comment]
Installing last release (after building it) did not worked. It said: "App not installed". 
My android version changed since my last comment. It is now Android 8.1.
It worked in debug mode using ../gradlew installDebug
The installed version is 1.3.2

Maybe there is an option blocking the installation of unknown APP in Android
