### ISSUE TITLE
Port Number not available in settings UI

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-android#17]
There appears to be no way in the admin/preference UI to set or discover the port number. Is there a default? If so, the port number should be shown on the general settings along with the IP address, so that one knows how to connect to it.

**Comment by alexrobin** [comment]
The port number can be included as part of the URL. If none is specified,
the default port for the specified protocol is used (i.e. 80 for http, 443
for https, as per the URL convention)

**Comment by alexrobin** [comment]
There was actually an issue to properly use the default port number. This has now been fixed
