### ISSUE TITLE
SensorHub not working on Android 4.4

### ISSUE THREAD

**Issue by sensiasoft** [opensensorhub/osh-android#2]
<a href="https://github.com/sensiasoft"><img src="https://avatars.githubusercontent.com/u/9446498?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sensiasoft](https://github.com/sensiasoft)**
_Friday Aug 21, 2015 at 08:31 GMT_
_Originally opened as https://github.com/sensiasoft/sensorhub-core/issues/29_

---

The app crashes on startup. It seems the external .dex file cannot be properly loaded using the Dexter technique. It looks like references to the classes contained in the dex files are needed during DEX compile, before the dex file is actually loaded.

**Comment by alexrobin** [comment]
Android 4.4 is super old by now so not worth it!
