### ISSUE TITLE
Hard to connect to Trupulse Laser Range Finder

### ISSUE THREAD

**Issue by alexrobin** [opensensorhub/osh-android#8]
Connecting to the Bluetooth LRF often doesn't work on starting OSH from the app. The message "Waiting for Trupulse ..." is shown on the screen and often never disappears. No data is received and sent to the remote server. Making it work seems to require restarting the app multiple times until the message "rangeData: NO OBS" is displayed.

**Comment by mikebotts** [comment]
This issue has increased in importance as both SOFWERX and NYS are interested in it. Could never get it to work on Pixel2 and the 1+6T.

**Comment by alexrobin** [comment]
A fix was put to better handle disconnecting from TruPulse bluetooth when OSH is turned off. This was the main problem preventing a proper reconnection to TruPulse when OSH was turned off and then back on.
